server:
  port: 8102

spring:
  application:
    name: schoolhelp-course
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/schoolhelpdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: sgtxgx
    password: sgtxgx123!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

schoolhelp:
  file:
    upload-dir: D:/homework/schoolHelp/schoolHelp/schoolhelp-course/uploads
    base-url: /files
